common/models/Truckers.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for collection "truckers".
 *
 * @property \MongoId|string $_id
 * @property mixed $name
 * @property mixed $contact
 * @property mixed $password
 * @property mixed $image
 * @property mixed $created_by
 * @property mixed $status
 * @property mixed $created_on
 * @property mixed $modified_on
 */
class Truckers extends \yii\mongodb\ActiveRecord
{
     public $firstname, $lastname, $email, $mobile_number;
    
    /**
     * @inheritdoc
     */
    public static function collectionName()
    {
        return [Yii::$app->mongodb->defaultDatabaseName, 'truckers'];
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        return [
            '_id',
            'name',
            'contact',
            'password',
            'image',
            'created_by',
            'status',
            'created_on',
            'modified_on',
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
//            [['firstname', 'lastname', 'email', 'mobile_number', 'business_name', 'registered_address', 'office_address', 'landline_number','business_pancard', 'password', 'account_type', 'company_type', 'business_type', 'pancard', 'status', 'role'], 'required'],
//            [['mobile_number', 'landline_number'], 'integer'],
//            [['email'], 'email'],
//            [['mobile_number','landline_number'], 'string', 'length' => [8, 15]],            
            [['name', 'contact', 'password', 'image', 'created_by', 'status', 'created_on', 'modified_on'], 'safe']
        ];
    }

     /**
     * @inheritdoc
     */
    public function attributeType()
    {
        return [

        ];
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            '_id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'contact' => Yii::t('app', 'Contact'),
            'password' => Yii::t('app', 'Password'),
            'image' => Yii::t('app', 'Image'),
            'created_by' => Yii::t('app', 'Created By'),
            'status' => Yii::t('app', 'Status'),
            'created_on' => Yii::t('app', 'Created On'),
            'modified_on' => Yii::t('app', 'Modified On'),
        ];
    }
}

backend/controllers/TruckerController.php
<?php
namespace backend\controllers;
use Yii;
use yii\filters\AccessControl;
use common\models\Users;
use common\models\UsersSearch;
use common\models\Common;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * TruckerController implements the CRUD actions for Users model.
 */
class TruckerController extends Controller{

    public function behaviors(){
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [''],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'delete', 'changestatus', 'changecp','actrkr'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }	

    /**
    * Lists all Users models.
    * @return mixed
    */
    public function actionIndex(){
		$searchModel = new UsersSearch();
		$params = Yii::$app->request->queryParams;
		if(empty($params['UsersSearch']['role'] ))		
			$params['UsersSearch']['role'] = [11,12]; // to fetch Truckers & Agent Users;
		// $params['UsersSearch']['status'] = [0,1];
        $dataProvider = $searchModel->search($params);
		if(empty(Yii::$app->request->queryParams['sort'])) $dataProvider->query->orderBy('created_on DESC'); // Sorting on the bases of creation date
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }	

    /**
     * Displays a single Users model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
		$model= $this->findModel($id);
	    $model->scenario = Users::SCENARIO_TRUCKER_VIEW;
        return $this->render('view', [
            'model' =>$model,
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
		return $this->redirect(['index']); // returns to the index function
        $model = new Users();
        $model->scenario = Users::SCENARIO_TRUCKER_CREATE;
        if($model->load(Yii::$app->request->post())){
			// $model->role = $_POST['Users']['account_type'];
            $model->save(false);
			$this->uploadImage($model,'image', true);
			$this->uploadImage($model,'business_logo', true);
            return $this->redirect(['index']);
            // return $this->redirect(['view', 'id' => (string)$model->_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		$model = $this->findModel($id);
		$model->scenario = Users::SCENARIO_TRUCKER_UPDATE;
		$oldPassword = $model->password; //Capture the old password.
		$model->password = '';
         if ($model->load(Yii::$app->request->post())) {
			 if(isset($_POST['Users']['role'])) $model->role = $model->account_type = $_POST['Users']['role'];
            $model->save(false);
			$this->uploadImage($model,'image', true);
			$this->uploadImage($model,'business_logo', true);
			return $this->redirect(['view', 'id' => (string)$model->_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionDelete($id){
		return $this->redirect(['index']); // returns to the index function
        $model = $this->findModel($id);
        $model->status = 0; // Deleted
		if(isset($model->has_cp))
		$model->has_cp = $model->oldAttributes['has_cp'];
        $model->save(false);
    }
	
    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $_id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
			// echo "<pre>"; print_r($model); exit;
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
	
        /**
    * Change the Status 
    * @param integer $_id
    * @return true/false
    */
    public function actionChangestatus(){
        $id  = Yii::$app->request->post('id');
        $model = $this->findModel($id);
        if($model->status == 'Active')
            $model->status = 0;
        else $model->status = 1;
		$model->has_cp = $model->oldAttributes['has_cp'];
        return $model->save(false);
    }

    /**
    * Change the Status 
    * @param integer $_id
    * @return true/false
    */
    public function actionChangecp(){
        $id  = Yii::$app->request->post('id');
        $model = $this->findModel($id);
        if($model->has_cp == 'Yes')
            $model->has_cp = 0;
        else $model->has_cp = 1;
		$model->status = $model->oldAttributes['status'];
        return $model->save(false);
    }	
	

	    /**
    * upload image to the specified directory
    * @params $model Volumn Model , $stat must be boolean true=Create,false=Update
    **/ 
    private function uploadImage($model,$colum, $stat=false){
        $path  = Common::mkdir($model::PARENTDIR.$model::CHILDDIR."-".$model->_id, 0755, true);
        $image = UploadedFile::getInstance($model, $colum);
        if(!empty($image)){
            if(!$stat){
                $oldImage = empty($model->oldAttributes[$colum]) ? '' : $model->oldAttributes[$colum];
                Common::DelFile($path.DS.$oldImage);
            }
            $model->$colum  = $colum.'_'.time().".".$image->extension; //die('as');
            $image->saveAs($path.DS.$model->$colum);
            $model->save(false); return true;
        }elseif(!$image && !$stat) $model->$colum = empty($model->oldAttributes[$colum]) ? '' : $model->oldAttributes[$colum] ; return true;
    }

}

backend/controllers/TruckersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Truckers;
use common\models\TruckersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TruckersController implements the CRUD actions for Truckers model.
 */
class TruckersController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Truckers models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TruckersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Truckers model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Truckers model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Truckers();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => (string)$model->_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Truckers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => (string)$model->_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Truckers model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Truckers model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $_id
     * @return Truckers the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Truckers::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/TruckerController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\models\Users;
use common\models\Common;
use common\models\VehiclesSearch;
use common\models\DriversSearch;
use common\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
/**
 * TruckerController implements the CRUD actions for Users model.
 */
class TruckerController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [''], //Put the actions here which you don't want to authenticate
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index','update'], //Put the actions here which you want to authenticate
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ], 
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VehiclesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
		$drivers_searchModel = new DriversSearch();
        $drivers_dataProvider = $drivers_searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'drivers_searchModel' => $drivers_searchModel,
            'drivers_dataProvider' => $drivers_dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $_id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => (string)$model->_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$model->scenario = Users::SCENARIO_TRUCKER_UPDATE;
        unset($model->password); 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			$this->uploadImage($model,'image');
			$this->uploadImage($model,'business_logo');
			Yii::$app->session->setFlash('flash_msg',"Record updated successfully.");
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
	 /**
    * upload image to the specified directory
    * @params $model Volumn Model , $stat must be boolean true=Create,false=Update
    **/ 
    private function uploadImage($model, $key){
        $path  = Common::mkdir($model::PARENTDIR.$model::CHILDDIR."-".$model->_id, 0755, true);
        $image = UploadedFile::getInstance($model, $key);
        if(!empty($image)){                    
            if($key=="business_logo"){
			   (empty($model->oldAttributes['business'][$key]) && $filename = time().".".$image->extension) ||                             $filename = $model->oldAttributes['business'][$key];
			}else{
			   (empty($model->oldAttributes[$key]) && $filename = time().".".$image->extension) ||                             $filename = $model->oldAttributes[$key];				
			}        
                    $model->$key  = $filename;
                    $image->saveAs($path.DS.$model->$key);
			        unset($model->password);
                    $model->save(false);
	    }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $_id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash('flash_msg',"Record deleted successfully.");
        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $_id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/trucker/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, '_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'contact') ?>

    <?= $form->field($model, 'otp') ?>

    <?= $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'mobile_tokens') ?>

    <?php // echo $form->field($model, 'hash_token') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'account_type') ?>

    <?php // echo $form->field($model, 'company_type') ?>

    <?php // echo $form->field($model, 'business_type') ?>

    <?php // echo $form->field($model, 'business') ?>

    <?php // echo $form->field($model, 'pancard') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'role') ?>

    <?php // echo $form->field($model, 'social') ?>

    <?php // echo $form->field($model, 'created_on') ?>

    <?php // echo $form->field($model, 'modified_on') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/trucker/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/trucker/index.php
<?php
use yii\helpers\Html;
use common\models\Common;
use common\models\Vehicles;
use yii\helpers\Url;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php 
	if(Yii::$app->session->hasFlash('flash_msg')):
 ?>
<div class="flash-msg">
  <?=Yii::$app->session->getFlash('flash_msg')?>
</div>
<?php endif; ?>   
  <div class="col-md-4 col-xs-12 col-sm-5 pull-right text-center pR0 mT20 " >
  <div class="bg-primary pT10 pL10 pB10 bdrr">
    <div class="row">
      <div class="col-md-4 col-xs-12 text-center pL20">
        <img src="<?=Yii::$app->user->getImage()?>" class="img-circle img-responsive "/>
        <div class="fnt13 mT10 editlink text-left txtc mL15"><a href="<?=Url::to(['trucker/update','id'=>Yii::$app->user->getId()])?>"><div class="edit hidden-xs hidden-sm"></div>Edit profile</a></div>
      </div>  
      <div class="col-md-8 col-xs-12 mTx20">
        <h3 class="mT0">Welcome, <?=Yii::$app->user->getName()?></h3>
        <h4><?=Yii::$app->user->getCompany()?></h4>
        
       
         <div class="btn-logout pull-right mT20 fnt13 mR20">
		 <div class="logout hide"></div></div>
	   </div>
      </div>
      </div>


   </div> 
	<br style="clear:both;"/>  

</div>
  <div class="row mT20 mB50">
    <div class="col-md-5 col-md-offset-2">
		

		<div class="bg-primary pT10">
	<div class="row mB20">
		<div class="col-md-7">
		<h2 class="sub-header pL20">Your Trucks</h2>	
		</div>
		<div class="col-md-4 mT20">
			<a href="<?=Url::to(['vehicles/create'])?>" class="btn btn-default btn-default2"><span class="glyphicon glyphicon-plus"></span> Add Truck</a>
		</div>
		  </div>	  
      
          <div class="table-responsive truckers-none ">
              <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
          //  '_id',
            ['attribute'=>'truck_type','header'=>'Truck Type', 'filter'=>Vehicles::getTruckList()],
            ['attribute'=>'vehicle_number','header'=>'Vehicle Number'],
            'number',
            //'registration',
            // 'insurance',
            // 'owner_id',
            //['attribute' => 'status', 'filter' => [0=>'Inactive', 1=>'Active']],
            // 'created_on',
            // 'modified_on',

            ['class' => 'yii\grid\ActionColumn',
			'header'=>'Actions',
            'template' => '{update} {delete}',
			'buttons' => [

            //view button
            'update' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => Yii::t('app', 'Edit'),
                            //'class'=>'btn btn-primary btn-xs',                                  
                ]);
            },
        ],

        'urlCreator' => function ($action, $model, $key, $index) {
            if ($action === 'update')
                return Url::to(['vehicles/update','id'=>$model->_id->__toString()]);
			if ($action === 'delete')
                return Url::to(['vehicles/delete','id'=>$model->_id->__toString()]);		         

		}
        ],
        ],
    ]); ?>
          </div>
          </div>
    </div>  
    <div class="col-md-5">
      <div class="bg-primary pT10 ">
      <div class="row mB20">
		<div class="col-md-7">
		<h2 class="sub-header pL20">Your Drivers</h2>	
		</div>
		<div class="col-md-4 mT20">
			<a href="<?=Url::to(['drivers/create'])?>" class="btn btn-default btn-default2"><span class="glyphicon glyphicon-plus"></span> Add Driver</a>
		</div>
		  </div>
          <div class="table-responsive truckers-none">
   <?= GridView::widget([
        'dataProvider' => $drivers_dataProvider,
        'filterModel' => $drivers_searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'_id',
            'name.firstname',
            'licence.number',
            'permit.number',
            //'mobile_no',
            //'image',
            // 'truck_type',
            // 'permit',
            // 'address',
            // 'licence',
            // 'status',
            // 'created_on',
            // 'modified_on',

                  ['class' => 'yii\grid\ActionColumn',
			'header'=>'Actions',
            'template' => '{update} {delete}',
			'buttons' => [

            //view button
            'update' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => Yii::t('app', 'Edit'),
                            //'class'=>'btn btn-primary btn-xs',                                  
                ]);
            },
        ],

        'urlCreator' => function ($action, $model, $key, $index) {
            if ($action === 'update')
                return Url::to(['drivers/update','id'=>$model->_id->__toString()]);
			if ($action === 'delete')
                return Url::to(['drivers/delete','id'=>$model->_id->__toString()]);
				
          
		}
        ],
        ],
    ]); ?>
          </div>
    </div> 
  </div>
  </div> 

frontend/views/trucker/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = 'Update Users: ' . ' ' . $model->uname;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->uname, 'url' => ['view', 'id' => (string)$model->_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/trucker/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => (string)$model->_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => (string)$model->_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            '_id',
            'name',
            'contact',
            'otp',
            'password',
            'mobile_tokens',
            'hash_token',
            'image',
            'account_type',
            'company_type',
            'business_type',
            'business',
            'pancard',
            'status',
            'role',
            'social',
            'created_on',
            'modified_on',
        ],
    ]) ?>

</div>